services:
  - type: web
    name: terabox-resolver-api
    runtime: python
    region: singapore
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TERABOX_BASE_URL
        value: https://terabox.beer
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PORT
        value: 10000
